# Build the frontend
FROM node:24.3.0-alpine AS frontend_build

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm install
COPY frontend/. .
RUN npm run build

# Build the backend
FROM nginx:alpine AS production_nginx

COPY --from=frontend_build /app/frontend/dist /usr/share/nginx/html

COPY docker-compose/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]